import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import prettierConfig from 'eslint-config-prettier';

export default [
  {
    ignores: [
      '**/dist/',
      '**/node_modules/',
      '*.cjs',
      '**/.wrangler/',
      // Generated by `wrangler types`
      'server/worker-configuration.d.ts',
    ],
  },

  // Base JS recommended
  js.configs.recommended,

  // TypeScript files
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-undef': 'off', // TypeScript handles this
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          // `const { scenarios, ...meta } = lesson` is how fields are dropped here
          ignoreRestSiblings: true,
        },
      ],
    },
  },

  // Client: React hooks
  {
    files: ['client/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooksPlugin,
    },
    rules: {
      ...reactHooksPlugin.configs.recommended.rules,
      // eslint-plugin-react-hooks v7 enables the React Compiler rules by
      // default. The components predate them and violate them in ways that are
      // correct but not compiler-optimal; kept visible as warnings rather than
      // rewriting the UI inside a hosting migration.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
    },
  },

  // Prettier (disables conflicting rules)
  prettierConfig,
];
